### ISSUE TITLE
Compilation error with GCC 8.5.0

### ISSUE THREAD

**Issue by evvaletov** [lanl/GSM#16]
OS: Oracle Linux 8
Compiler: GNU Fortran (GCC) 8.5.0 20210514 (Red Hat 8.5.0-20.0.3)

I tried to compile the code following the instructions, but I'm getting the following output at the `make` stage:

Command: `make VERBOSE=1`
Output:
```
/usr/bin/cmake -S/home/evaletov/LANL/GSM -B/home/evaletov/LANL/GSM/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/evaletov/LANL/GSM/build/CMakeFiles /home/evaletov/LANL/GSM/build//CMakeFiles/progress.marks
make  -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/evaletov/LANL/GSM/build'
make  -f CMakeFiles/my_gsm.dir/build.make CMakeFiles/my_gsm.dir/depend
make[2]: Entering directory '/home/evaletov/LANL/GSM/build'
cd /home/evaletov/LANL/GSM/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/evaletov/LANL/GSM /home/evaletov/LANL/GSM /home/evaletov/LANL/GSM/build /home/evaletov/LANL/GSM/build /home/evaletov/LANL/GSM/build/CMakeFiles/my_gsm.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/evaletov/LANL/GSM/build'
make  -f CMakeFiles/my_gsm.dir/build.make CMakeFiles/my_gsm.dir/build
make[2]: Entering directory '/home/evaletov/LANL/GSM/build'
/usr/bin/cmake -E make_directory /home/evaletov/LANL/GSM/my_gsm
/usr/bin/cmake -E copy /home/evaletov/LANL/GSM/src/dataTbl/* /home/evaletov/LANL/GSM/my_gsm/
/usr/bin/cmake -E copy /home/evaletov/LANL/GSM/build/bin/xgsm* /home/evaletov/LANL/GSM/my_gsm/
Error copying file "/home/evaletov/LANL/GSM/build/bin/xgsm*" to "/home/evaletov/LANL/GSM/my_gsm/".
make[2]: *** [CMakeFiles/my_gsm.dir/build.make:72: CMakeFiles/my_gsm] Error 1
make[2]: Leaving directory '/home/evaletov/LANL/GSM/build'
make[1]: *** [CMakeFiles/Makefile2:447: CMakeFiles/my_gsm.dir/all] Error 2
make[1]: Leaving directory '/home/evaletov/LANL/GSM/build'
make: *** [Makefile:166: all] Error 2
```

**Comment by cmjuneau** [comment]
Hi @evvaletov!

Thanks for opening this issue. This is an interesting error; I'm not able to replicate it myself. In short, `make` is trying to build everything. The error you are specifically getting looks to be during the portion of making the "my_gsm" folder. Does `make xgsm1` give you the same error by chance?

 `make VERBOSE=1` is creating a simulation folder for you (as part of the `my_gsm` option). This copies the data files and the `xgsm*` executable to the `my_gsm` directory. Your error indicates it can't copy the `xgsm*` - does `/home/evaletov/LANL/GSM/build/bin/` have any files in it? If it has an `xgsm1`, what happens if you try to copy it directly (e.g., `cp /home/evaletov/LANL/GSM/build/bin/xgsm* /home/evaletov/LANL/GSM/my_gsm/`)?

Also, I recently discovered that GSM throws a segmentation fault on some newer version of gfortran. I'm able to build and execute this on gfortran 8.3.1 without any segmentation faults, so you'll probably be ok, but keep that in mind if you are using a different compiler.

**Comment by cmjuneau** [comment]
CMake files specified which compiler to use, which caused builds to fail when the compiler wasn't present. Removed this and additionally made some adjustments for compilation with gfortran 4.*. See #17 for details.
